version: "3.3"

services:
 redis:
  image: redis
  ports:
   - "6379"
  networks:
   - opnet
 
 pgsql:
  image: faisalthaheem/hurtrade-pgsql:v1.0.0-alpha
  environment:
   POSTGRES_PASSWORD: faisal123
  networks:
   - opnet
 
 webauth:
  image: faisalthaheem/hurtrade-webauth:v1.0.0-alpha
  environment:
   REDIS_SERVER: redis
   MQ_HOST: rabbitmq
   MQ_USERNAME: svc
   MQ_PASSWORD: svc
   DB_HOST: pgsql
   DB_USERNAME: postgres
   DB_PASSWORD: faisal123
  depends_on:
   - redis
   - pgsql
  ports:
   - "80"
  networks:
   - opnet
 
 rabbitmq:
  image: faisalthaheem/hurtrade-rabbitmq:v1.0.0-alpha
  depends_on:
   - webauth
  ports:
   - "5672:5672"
   - "15672:15672"
  networks:
   - opnet
 
 fxyahoo:
  image: faisalthaheem/hurtrade-fxyahoo:v1.0.0-alpha
  environment:
   REDIS_SERVER: redis
   MQ_HOST: rabbitmq
   MQ_USERNAME: svc
   MQ_PASSWORD: svc
   DB_HOST: pgsql
   DB_USERNAME: postgres
   DB_PASSWORD: faisal123
  depends_on:
   - redis
   - pgsql
   - rabbitmq
  networks:
   - opnet
 
 mqstats:
  image: faisalthaheem/hurtrade-mqstats:v1.0.0-alpha
  environment:
   MQ_HOST: rabbitmq
   MQ_USERNAME: svc
   MQ_PASSWORD: svc
   MQ_MGMT_BASE_URL: http://rabbitmq:15672
  depends_on:
   - redis
   - pgsql
   - rabbitmq
  networks:
   - opnet
 
 hurcpu:
  image: faisalthaheem/hurtrade-hurcpu:v1.0.0-alpha
  environment:
   REDIS_SERVER: redis
   MQ_HOST: rabbitmq
   MQ_USERNAME: svc
   MQ_PASSWORD: svc
   DB_HOST: pgsql
   DB_USERNAME: postgres
   DB_PASSWORD: faisal123
  depends_on:
   - redis
   - pgsql
   - rabbitmq
  networks:
   - opnet

networks:
 opnet:
